<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1521266110969' stop='1521266117715'>
    <name>To test the Angular binding functionality</name>
    <title>To test the Angular binding functionality</title>
    <test-cases>
        <test-case start='1521266110970' status='passed' stop='1521266114783'>
            <name>should not have any previous results</name>
            <title>should not have any previous results</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='da17b3da-3987-43f3-b738-a761856b828d-attachment.png' type='image/png' size='15605'/>
            </attachments>
        </test-case>
        <test-case start='1521266114783' status='failed' stop='1521266117714'>
            <name>Should display calculation results for performed Arthematic operations and should save results in table</name>
            <title>Should display calculation results for performed Arthematic operations and should save results in table</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='d443cca0-4e32-48c8-9536-f66fb7bd21a8-attachment.png' type='image/png' size='18162'/>
            </attachments>
            <failure>
                <message>Expected 0 to equal 1.</message>
                <stack-trace>Error: Failed expectation
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\specs\calculation_spec.js:33:28
                    at ManagedPromise.invokeCallback_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at &lt;anonymous>
                    at process._tickCallback (internal/process/next_tick.js:118:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1521266117714' status='pending' stop='1521266117715'>
            <name>Should display calculation results for performed Arthematic operations and should save new results in table</name>
            <title>Should display calculation results for performed Arthematic operations and should save new results in table</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Temporarily disabled with xit</message>
                <stack-trace></stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>