<?xml version='1.0'?>
<ns2:test-suite xmlns:ns2='urn:model.allure.qatools.yandex.ru' start='1521266503601' stop='1521266511145'>
    <name>To test the Angular binding functionality</name>
    <title>To test the Angular binding functionality</title>
    <test-cases>
        <test-case start='1521266503602' status='passed' stop='1521266507658'>
            <name>should not have any previous results</name>
            <title>should not have any previous results</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='68ffe1e1-8ad7-426b-b555-914dabc14244-attachment.png' type='image/png' size='15605'/>
            </attachments>
        </test-case>
        <test-case start='1521266507658' status='failed' stop='1521266511144'>
            <name>Should display calculation results for performed Arthematic operations and should save results in table</name>
            <title>Should display calculation results for performed Arthematic operations and should save results in table</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments>
                <attachment title='Screenshot' source='ae420e9b-dc78-4470-8d99-aca40a66e92f-attachment.png' type='image/png' size='18541'/>
            </attachments>
            <failure>
                <message>Expected '2' to equal '1'.</message>
                <stack-trace>Error: Failed expectation
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\specs\calculation_spec.js:34:34
                    at ManagedPromise.invokeCallback_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:1376:14)
                    at TaskQueue.execute_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3084:14)
                    at TaskQueue.executeNext_ (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:3067:27)
                    at asyncRun (C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:2927:27)
                    at C:\Users\sandeep\Desktop\Protractor\Protractor\node_modules\selenium-webdriver\lib\promise.js:668:7
                    at &lt;anonymous>
                    at process._tickCallback (internal/process/next_tick.js:118:7)</stack-trace>
            </failure>
        </test-case>
        <test-case start='1521266511144' status='pending' stop='1521266511144'>
            <name>Should display calculation results for performed Arthematic operations and should save new results in table</name>
            <title>Should display calculation results for performed Arthematic operations and should save new results in table</title>
            <labels/>
            <parameters/>
            <steps/>
            <attachments/>
            <failure>
                <message>Temporarily disabled with xit</message>
                <stack-trace></stack-trace>
            </failure>
        </test-case>
    </test-cases>
</ns2:test-suite>